TRUNCATE TABLE admin_entity
TRUNCATE TABLE school_entity
TRUNCATE TABLE student_entity
TRUNCATE TABLE student_school_subscription_entity
TRUNCATE TABLE school_feed_entity
TRUNCATE TABLE student_news_feed_entity